"""agregar dni a usuarios

Revision ID: 878665284b4e
Revises: 8e13afb9b180
Create Date: 2026-10-10 20:12:24.817334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '878665284b4e'
down_revision: Union[str, Sequence[str], None] = '8e13afb9b180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('dni', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'usuarios', ['dni'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'dni')
    # ### end Alembic commands ###
